### ISSUE TITLE
gulp and gulp publish error out on hugo:all

### ISSUE THREAD

**Issue by rootwork** [jbrodriguez/hugulp#5]
Installed as described in the README. Everything seemed to go smoothly, but when I ran `gulp` or `gulp publish` I get these errors:

```
'hugo:all' errored after 1.24 ms
TypeError: undefined is not a function
    at hugo (/[path]/gulp/hugo.js:18:18)
    at Gulp.<anonymous> (/[path]/gulp/hugo.js:27:5)
    at module.exports (/[path]/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/[path]/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/[path]/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /[path]/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/[path]/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /[path]/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/[path]/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/[path]/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
```

All the other gulp tasks completed successfully; it's something about the hugo task, and I think specifically the `hugo(drafts)` function.

This looks like a great project, but I'm not sure how to proceed from here. Let me know if there's any more information I can provide!

**Comment by jbrodriguez** [comment]
Hi @rootwork, it fails to execute the hugo invocation (this line https://github.com/jbrodriguez/hugulp/blob/master/gulp/hugo.js#L18)

Can you double check that all node modules are installed ?

It looks like this require call (https://github.com/jbrodriguez/hugulp/blob/master/gulp/hugo.js#L2) didn't work for some reason.

Try installing it directly and see how it goes (npm install child_process).

**Comment by rootwork** [comment]
That didn't work -- apparently child_process is part of node and can't be installed separately:

https://stackoverflow.com/questions/16872459/npm-install-child-process-not-working

But that made me think I might have an old node version that didn't have that function, and indeed I was on 0.10. Updating to node 0.12.7 fixed it.

Sorry for the noise!
