### ISSUE TITLE
imagemin bombs

### ISSUE THREAD

**Issue by yitzhakbg** [jbrodriguez/hugulp#7]
```
.pipe(imagemin()) in gulp/images.js is the culprit
```

~/hugulp » gulp
[07:31:21] Using gulpfile ~/hugulp/gulpfile.js
[07:31:21] Starting 'styles'...
[07:31:21] Starting 'scripts'...
[07:31:21] Starting 'images'...
[07:31:21] Starting 'svg'...
[07:31:21] Finished 'styles' after 63 ms
[07:31:21] Finished 'svg' after 27 ms

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/ybg/hugulp/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
~/hugulp »

**Comment by jbrodriguez** [comment]
Hi @yitzhakbg, imagemin hasn't changed recently, so it's a bit of a mistery that it failed.

Can you try installing it manually and see if it solves it

```
$ npm install --save gulp-imagemin
```

**Comment by yitzhakbg** [comment]
Perhaps a system issue. Running Ubuntu 15.10. Don’t worry. It’s not critical for now. BTW, kudos on the nice two part tutorial. Oh, and another thing, it doesn’t like already minified js script files
Best,
Yitzhak

After uninstall:
~/hugulp » npm install gulp-imagemin --save                                                                                                      master ✗
npm WARN package.json hugulp@0.1.0 No repository field.
/

> optipng-bin@3.0.2 postinstall /home/ybg/hugulp/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

Same thing:
~/hugulp » gulp                                                                                                                                  master ✗
[11:20:57] Using gulpfile ~/hugulp/gulpfile.js
[11:20:57] Starting 'styles'...
[11:20:57] Starting 'scripts'...
[11:20:57] Starting 'images'...
[11:20:57] Starting 'svg'...
[11:20:57] Finished 'styles' after 63 ms
[11:20:57] Finished 'svg' after 46 ms

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/ybg/hugulp/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)

**Comment by jbrodriguez** [comment]
Ok, got it.

Hopefully is a system issue like you said.

 Thanks for the kudos !
